name: Compile Sketch

on:
  - push
  - pull_request

jobs:
  compile-sketch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:
          platforms: |
            - source-url: "https://github.com/SpenceKonde/ATTinyCore/archive/1.4.1.zip"
              name: "ATTinyCore:avr"
            - name: "arduino:avr"
          sketch-paths: |
            - src/berlin-uhr
          fqbn: "ATTinyCore:avr:attinyx7:chip=167"
